//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoTodoListClient.ToDoListService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ToDoItem", Namespace="http://schemas.datacontract.org/2004/07/ToDoList")]
    [System.SerializableAttribute()]
    public partial class ToDoItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        private string TittleField;
        
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Tittle {
            get {
                return this.TittleField;
            }
            set {
                if ((object.ReferenceEquals(this.TittleField, value) != true)) {
                    this.TittleField = value;
                    this.RaisePropertyChanged("Tittle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ToDoListService.ITodoListService")]
    public interface ITodoListService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/GetItem", ReplyAction="http://tempuri.org/ITodoListService/GetItemResponse")]
        System.Collections.Generic.List<DemoTodoListClient.ToDoListService.ToDoItem> GetItem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/GetItem", ReplyAction="http://tempuri.org/ITodoListService/GetItemResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<DemoTodoListClient.ToDoListService.ToDoItem>> GetItemAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/CreateItem", ReplyAction="http://tempuri.org/ITodoListService/CreateItemResponse")]
        string CreateItem(DemoTodoListClient.ToDoListService.ToDoItem item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITodoListService/CreateItem", ReplyAction="http://tempuri.org/ITodoListService/CreateItemResponse")]
        System.Threading.Tasks.Task<string> CreateItemAsync(DemoTodoListClient.ToDoListService.ToDoItem item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITodoListServiceChannel : DemoTodoListClient.ToDoListService.ITodoListService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TodoListServiceClient : System.ServiceModel.ClientBase<DemoTodoListClient.ToDoListService.ITodoListService>, DemoTodoListClient.ToDoListService.ITodoListService {
        
        public TodoListServiceClient() {
        }
        
        public TodoListServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TodoListServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoListServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TodoListServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DemoTodoListClient.ToDoListService.ToDoItem> GetItem() {
            return base.Channel.GetItem();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<DemoTodoListClient.ToDoListService.ToDoItem>> GetItemAsync() {
            return base.Channel.GetItemAsync();
        }
        
        public string CreateItem(DemoTodoListClient.ToDoListService.ToDoItem item) {
            return base.Channel.CreateItem(item);
        }
        
        public System.Threading.Tasks.Task<string> CreateItemAsync(DemoTodoListClient.ToDoListService.ToDoItem item) {
            return base.Channel.CreateItemAsync(item);
        }
    }
}
